config/routes.rb
Rails.application.routes.draw do
  root "activities#index"
  
  get 'activities/filter_group', to: 'activity_filters#new_group'
  get 'activities/filter_condition', to: 'activity_filters#new_condition'
  
  resources :activities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/activity.rb
class Activity < ApplicationRecord
  def kind_value
    { 1 => "Melhoria", 2 => "Bug", 3 => "Spike", 4 => "Documentação", 5 => "Reunião" }[self.kind]
  end

  def urgency_value
    { 1 => "Alto", 2 => "Médio", 3 => "Baixo" }[self.urgency]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  include ActivityFiltersHelper
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all.order(:start_date)
    @filters = { operator: 'AND', groups: [] }
    
    begin
      if params[:filters].present? && params[:filters][:operator].present?
        @filters[:operator] = params[:filters][:operator]
      end

      if params[:groups].present?
        groups = params.require(:groups).values.map do |group_params|
          {
            operator: group_params[:operator] || 'AND',
            filters: (group_params[:filters] || {}).values.map do |filter_params|
              {
                field: filter_params[:field],
                value: Array(filter_params[:value]).reject(&:blank?)
              }
            end
          }
        end
        @filters[:groups] = groups
      elsif params[:filters].present?
        @filters = params.require(:filters).permit(
          :operator,
          groups: [
            :operator,
            { filters: [:field, { value: [] }] }
          ]
        ).to_h.deep_symbolize_keys
      end
    rescue => e
      Rails.logger.error e.backtrace.join("\n")
    end

    if @filters[:groups].present? && @filters[:groups].any? { |g| g[:filters].present? }
      @activities = ActivityFilterBuilder.new(@activities, @filters).apply
    end

    @filter_groups = if @filters[:groups].present? && @filters[:groups].any? { |g| g[:filters].present? }
      @filters[:operator] = @filters[:operator] || 'AND'
      @filters[:groups].map do |group|
        FilterGroup.new(
          operator: group[:operator] || 'AND',
          filters: group[:filters].map do |filter|
            FilterCondition.new(
              field: filter[:field],
              value: filter[:value]
            )
          end
        )
      end
    else
      [FilterGroup.new(filters: [FilterCondition.new], operator: 'AND')]
    end
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy!

    respond_to do |format|
      format.html { redirect_to activities_path, status: :see_other, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.expect(activity: [ :title, :description, :status, :start_date, :end_date, :kind, :completed_percent, :priority, :urgency, :points ])
    end
end

app/controllers/activity_filters_controller.rb
class ActivityFiltersController < ApplicationController
  # GET /activities/filter_group
  def new_group
    @group_index = params[:index].to_i
    @group_operator = params[:global_operator] || 'AND'
    @group = FilterGroup.new(filters: [FilterCondition.new], operator: 'OR')

    render partial: "activities/filter/filter_group", 
           locals: { 
             group: @group, 
             group_index: @group_index,
             group_operator: @group_operator
           }
  end

  # GET /activities/filter_condition
  def new_condition
    @group_index = params[:group_index].to_i
    @condition_index = params[:condition_index].to_i
    @group = FilterGroup.new(operator: 'OR')
    
    field = params[:field]
    # temp, so pra renderizar o input
    @condition = FilterCondition.new(field: field, value: [])

    render partial: "activities/filter/filter_condition", 
           locals: { 
             condition: @condition, 
             group_index: @group_index, 
             condition_index: @condition_index,
             operator: @group.operator
           }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_filters_helper.rb
module ActivityFiltersHelper
  def field_label(field)
    {
      "title" => "Título",
      "description" => "Descrição",
      "status" => "Status",
      "start_date" => "Data de início",
      "end_date" => "Data de término",
      "kind" => "Tipo",
      "completed_percent" => "Percentual concluído",
      "priority" => "Prioridade",
      "urgency" => "Urgência",
      "points" => "Pontos",
      "user_id" => "Responsável"
    }[field]
  end

  def operator_label(operator)
    {
      "AND" => "E",
      "OR" => "OU"
    }[operator]
  end

  def field_type(field)
    {
      "title" => "text",
      "description" => "text",
      "status" => "select",
      "start_date" => "date",
      "end_date" => "date",
      "kind" => "select",
      "completed_percent" => "number",
      "priority" => "number",
      "urgency" => "select",
      "points" => "number",
      "user_id" => "select"
    }[field]
  end

  def field_options(field)
    field = field.to_s
    if field == "user_id"
      User.all.map { |user| { value: user.id, label: user.name } }
    else
      {
        "status" => [
          { value: 1, label: "Entregue" },
          { value: 0, label: "Em andamento" }
        ],
        "kind" => [
          { value: 1, label: "Melhoria" },
          { value: 2, label: "Bug" },
          { value: 3, label: "Spike" },
          { value: 4, label: "Documentação" },
          { value: 5, label: "Reunião" }
        ],
        "urgency" => [
          { value: 1, label: "Alto" },
          { value: 2, label: "Médio" },
          { value: 3, label: "Baixo" }
        ]
      }[field]
    end
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>">
  <p>
    <strong>Título:</strong>
    <%= activity.title %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= activity.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= activity.status %>
  </p>

  <p>
    <strong>Início:</strong>
    <%= activity.start_date %>
  </p>

  <p>
    <strong>Término:</strong>
    <%= activity.end_date %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= activity.kind_value %>
  </p>

  <p>
    <strong>% Completo%:</strong>
    <%= activity.completed_percent %>
  </p>

  <p>
    <strong>Prioridade:</strong>
    <%= activity.priority %>
  </p>

  <p>
    <strong>Urgência:</strong>
    <%= activity.urgency_value %>
  </p>

  <p>
    <strong>Pontos:</strong>
    <%= activity.points %>
  </p>

</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.checkbox :status %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :kind, style: "display: block" %>
    <%= form.number_field :kind %>
  </div>

  <div>
    <%= form.label :completed_percent, style: "display: block" %>
    <%= form.text_field :completed_percent %>
  </div>

  <div>
    <%= form.label :priority, style: "display: block" %>
    <%= form.number_field :priority %>
  </div>

  <div>
    <%= form.label :urgency, style: "display: block" %>
    <%= form.number_field :urgency %>
  </div>

  <div>
    <%= form.label :points, style: "display: block" %>
    <%= form.number_field :points %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<% content_for :title, "Editing activity" %>

<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/filter/_activity_filter.html.erb
<%= form_with url: activities_path, method: :get, data: { controller: "filter" } do |f| %>
  <%= f.hidden_field :operator, value: @filters[:operator] || 'AND', name: "filters[operator]" %>

  <div id="filter-groups-container" data-filter-target="container">
    <% @filter_groups.each_with_index do |group, group_index| %>
      <%= render "activities/filter/filter_group",
            group: group,
            group_index: group_index,
            group_operator: @filters[:operator] || 'AND' %>
    <% end %>
  </div>

  <div class="modal-footer">
    <div class="d-flex w-100 justify-content-between">
      <button type="button" class="btn btn-outline-secondary btn-sm" data-action="filter#addGroup">
        +  Adicionar grupo
      </button>

      <div class="d-flex gap-2">
        <button type="button" class="btn btn-outline-secondary btn-sm border-0" data-action="filter#clearFilters">
          Limpar filtros
        </button>
        <%= submit_tag "Aplicar filtros", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/activities/filter/_filter_condition.html.erb
<div class="filter-condition mb-2 p-3" 
     data-controller="condition"
     data-group-index="<%= group_index %>"
     data-condition-index="<%= condition_index %>">

  <div class="row g-2 align-items-end">
    <div class="col" style="max-width: 100px">
      <% if condition_index.zero? %>
        <p>Onde</p>
      <% elsif condition_index == 1 %>
        <select name="groups[<%= group_index %>][operator]" class="form-select" data-action="change->condition#toggleConditionOperator">
          <option value="AND" <%= 'selected' if (defined?(group) && group.operator == 'AND') || operator == 'AND' %>>E</option>
          <option value="OR" <%= 'selected' if (defined?(group) && group.operator == 'OR') || operator == 'OR' %>>Ou</option>
        </select>
      <% else %>
        <p 
        data-filter-target="operatorDisplay" 
           data-condition-index="<%= condition_index %>"
           data-group-index="<%= group_index %>"
        >
          <%= operator.presence || '—' %>
          </p>
      <% end %>
    </div>

    <div class="col">
      <% fields = %w[title description status start_date end_date kind completed_percent priority urgency points user_id] %>
      <%= select_tag "groups[#{group_index}][filters][#{condition_index}][field]",
            options_for_select(fields.map { |f| [field_label(f), f] }, condition.field),
            include_blank: "Selecione o campo",
            class: "form-select",
            data: { 
              action: "change->condition#toggleField",
              condition_target: "fieldSelect"
            } %>
    </div>

    <div class="col" data-condition-target="valueWrapper">
      <% fields.each do |f| %>
        <div data-condition-target="inputWrapper" data-field="<%= f %>" class="d-none">
          <% type = field_type(f) rescue 'text' %>

          <% if type == "text" %>
            <%= text_field_tag "groups[#{group_index}][filters][#{condition_index}][value][]", condition.value&.first, class: "form-control", placeholder: "Valor do campo" %>
          <% elsif type == "number" %>
            <%= number_field_tag "groups[#{group_index}][filters][#{condition_index}][value][]", condition.value&.first, class: "form-control", placeholder: "Valor do campo" %>
          <% elsif type == "date" %>
            <%= date_field_tag "groups[#{group_index}][filters][#{condition_index}][value][]", condition.value&.first, class: "form-control" %>
          <% elsif type == "select" %>
          <%= select_tag(
            "groups[#{group_index}][filters][#{condition_index}][value][]",
            options_for_select(field_options(f)&.map { |opt| [opt[:label], opt[:value]] }, condition.value&.first),
            class: "form-select"
          ) %>
        <% end %>
        </div>
      <% end %>
    </div>

    <div class="col-auto">
      <button type="button" class="btn btn-sm remove-condition" data-action="group#removeCondition">
        <span class="material-symbols-outlined fs-6 text-center color-secondary">delete</span>
      </button>
    </div>
  </div>
</div>

app/views/activities/filter/_filter_group.html.erb
<div class="filter-group mb-3 row" data-controller="group" data-group-index="<%= group_index %>">
  <div class="col-2">
    <% if group_index.zero? %>
      <p class="pt-3">Onde</p>
    <% elsif group_index == 1 %>
      <select 
        name="group_operator"
        class="form-select"
        data-action="change->group#toggleConditionOperator"
        data-filter-target="groupOperatorSelect"
        data-group-index="<%= group_index %>"
      >
        <option value="AND" <%= 'selected' if group_operator == 'AND' %>>E</option>
        <option value="OR" <%= 'selected' if group_operator == 'OR' %>>Ou</option>
      </select>
    <% else %>
      <p style="text-align: center;" data-filter-target="groupOperatorDisplay"><%= group_operator %></p>
    <% end %>
  </div>

  <div class=" col position-relative rounded" style="background-color: #edf2f7;">
    <div class="conditions-container">
      <% group.filters.each_with_index do |condition, condition_index| %>
        <%= render "activities/filter/filter_condition", 
              condition: condition, 
              group_index: group_index, 
              condition_index: condition_index,
              operator: group.operator %>
      <% end %>
    </div>

    <button type="button" class="btn btn-outline-secondary mt-2 mb-3 add-condition fs-6 border-0" 
            data-action="group#addCondition" 
            data-group-index="<%= group_index %>">
      + Adicionar filtro agrupado
    </button>
  </div>
</div>

app/views/activities/index.html.erb
<% content_for :title, "Activities" %>

<h1>Atividades</h1>

<p style="color: green"><%= notice %></p>

<div style="margin-bottom: 1em; display: flex; justify-content: space-between">
  <%= link_to "Nova atividade", new_activity_path, class: "btn btn-primary" %>

  <!-- Botão que abre o modal -->
  <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#filterModal">
    Filtrar
  </button>

  <%= render partial: "shared/modal",
    locals: { 
      modal_id: "filterModal",
      title: "Filtrar indicador",
      body: "activities/filter/activity_filter",
      body_locals: { groups: @filter_groups, group_operator: @filters[:operator] },
    } %>

</div>

<div style="overflow-x: auto; border: 1px solid #ccc; border-radius: 6px;">
  <table style="width: 100%; min-width: 1000px; border-collapse: collapse;">
    <thead style="background-color: #f2f2f2;">
      <tr>
        <th style="padding: 8px; text-align: left;">ID</th>
        <th style="padding: 8px; text-align: left;">Título</th>
        <th style="padding: 8px; text-align: left;">Descrição</th>
        <th style="padding: 8px; text-align: left;">Status</th>
        <th style="padding: 8px; text-align: left;">Início</th>
        <th style="padding: 8px; text-align: left;">Término</th>
        <th style="padding: 8px; text-align: left;">Tipo</th>
        <th style="padding: 8px; text-align: left;">% Completo</th>
        <th style="padding: 8px; text-align: left;">Prioridade</th>
        <th style="padding: 8px; text-align: left;">Urgência</th>
        <th style="padding: 8px; text-align: left;">Pontos</th>
        <th style="padding: 8px; text-align: left;">Responsável</th>
        <th style="padding: 8px; text-align: left;">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @activities.each do |activity| %>
        <tr style="border-top: 1px solid #ddd;">
          <td style="padding: 8px;"><%= activity.id %></td>
          <td style="padding: 8px;"><%= activity.title %></td>
          <td style="padding: 8px;"><%= truncate(activity.description, length: 50) %></td>
          <td style="padding: 8px;"><%= activity.status ? '✅' : '❌' %></td>
          <td style="padding: 8px;"><%= activity.start_date %></td>
          <td style="padding: 8px;"><%= activity.end_date %></td>
          <td style="padding: 8px;"><%= activity.kind_value %></td>
          <td style="padding: 8px;"><%= activity.completed_percent %> %</td>
          <td style="padding: 8px;"><%= activity.priority %></td>
          <td style="padding: 8px;"><%= activity.urgency_value %></td>
          <td style="padding: 8px;"><%= activity.points %></td>
          <td style="padding: 8px;"><%= activity.user_id %></td>
          <td style="padding: 8px;">
            <%= link_to 'Show', activity, style: "margin-right: 6px;" %>
            <%= link_to 'Edit', edit_activity_path(activity), style: "margin-right: 6px;" %>
            <%= link_to 'Delete', activity, method: :delete, data: { confirm: 'Tem certeza?' }, style: "color: red;" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/activities/new.html.erb
<% content_for :title, "Nova atividade" %>

<h1>Nova atividade</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Voltar", activities_path %>
</div>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%= link_to "Editar", edit_activity_path(@activity) %> |
  <%= link_to "Voltar", activities_path %>

  <%= button_to "Deletar", @activity, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# BOOTSTRAP %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

    <%# MATERIAL SYMBOLS ICON %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="padding: 16px">
    <%= yield %>
  </body>
</html>

app/views/shared/_modal.html.erb
  <div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= title %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
        </div>
        <div class="modal-body">
          <%= render body, **(body_locals || {}) %>
        </div>
      </div>
    </div>
  </div>